# Convert a flat binary into a C source/header pair that embeds it as an array.
# Usage:
#   cmake -DINPUT_FILE=<bin> -DOUTPUT_C=<c file> -DOUTPUT_H=<header> -P BinToC.cmake
if(NOT INPUT_FILE OR NOT OUTPUT_C OR NOT OUTPUT_H)
    message(FATAL_ERROR "BinToC.cmake requires INPUT_FILE, OUTPUT_C and OUTPUT_H.")
endif()

file(READ "${INPUT_FILE}" blob_hex HEX)
string(LENGTH "${blob_hex}" blob_hex_length)
math(EXPR blob_size "${blob_hex_length} / 2")
if(blob_size EQUAL 0)
    message(FATAL_ERROR "BinToC.cmake: ${INPUT_FILE} is empty.")
endif()

# Wrap into rows of 12 bytes for readability (CMake regex has no {n} quantifier).
set(blob_rows "")
set(byte_index 0)
while(byte_index LESS blob_size)
    math(EXPR row_last "${byte_index} + 12")
    set(row "")
    while(byte_index LESS blob_size AND byte_index LESS row_last)
        math(EXPR hex_index "${byte_index} * 2")
        string(SUBSTRING "${blob_hex}" ${hex_index} 2 byte_hex)
        string(APPEND row "0x${byte_hex},")
        math(EXPR byte_index "${byte_index} + 1")
    endwhile()
    string(APPEND blob_rows "    ${row}\n")
endwhile()

get_filename_component(header_name "${OUTPUT_H}" NAME)
file(WRITE "${OUTPUT_C}"
"/* Auto-generated by cmake/BinToC.cmake. Do not edit. */
#include \"${header_name}\"

const unsigned char kRuntimeLoaderStub[] = {
${blob_rows}};

const unsigned int kRuntimeLoaderStubSize = ${blob_size}u;
")
file(WRITE "${OUTPUT_H}"
"/* Auto-generated by cmake/BinToC.cmake. Do not edit. */
#ifndef RUNTIME_LOADER_STUB_BLOB_H
#define RUNTIME_LOADER_STUB_BLOB_H

extern const unsigned char kRuntimeLoaderStub[];
extern const unsigned int kRuntimeLoaderStubSize;

#endif
")
