# Convert a flat binary into a C source/header pair that embeds it as an array.
# Usage:
#   cmake -DINPUT_FILE=<bin> -DOUTPUT_C=<c file> -DOUTPUT_H=<header> -P BinToC.cmake
if(NOT INPUT_FILE OR NOT OUTPUT_C OR NOT OUTPUT_H)
    message(FATAL_ERROR "BinToC.cmake requires INPUT_FILE, OUTPUT_C and OUTPUT_H.")
endif()

file(READ "${INPUT_FILE}" blob_hex HEX)
string(LENGTH "${blob_hex}" blob_hex_length)
math(EXPR blob_size "${blob_hex_length} / 2")
if(blob_size EQUAL 0)
    message(FATAL_ERROR "BinToC.cmake: ${INPUT_FILE} is empty.")
endif()

string(REGEX REPLACE "(..)" "0x\\1," blob_bytes "${blob_hex}")
string(REGEX REPLACE "((0x..,){12})" "\\1\n    " blob_bytes "${blob_bytes}")

get_filename_component(header_name "${OUTPUT_H}" NAME)
file(WRITE "${OUTPUT_C}"
"/* Auto-generated by cmake/BinToC.cmake. Do not edit. */
#include \"${header_name}\"

const unsigned char kRuntimeLoaderStub[] = {
    ${blob_bytes}
};

const unsigned int kRuntimeLoaderStubSize = ${blob_size}u;
")
file(WRITE "${OUTPUT_H}"
"/* Auto-generated by cmake/BinToC.cmake. Do not edit. */
#ifndef RUNTIME_LOADER_STUB_BLOB_H
#define RUNTIME_LOADER_STUB_BLOB_H

extern const unsigned char kRuntimeLoaderStub[];
extern const unsigned int kRuntimeLoaderStubSize;

#endif
")
