set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

add_compile_options(
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<OR:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:/GL>
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<OR:$<C_COMPILER_ID:GNU>,$<C_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:-flto>
)
add_compile_options(
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<OR:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>>:/utf-8>
)
add_link_options(
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<C_COMPILER_ID:MSVC>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:/LTCG>
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<OR:$<C_COMPILER_ID:GNU>,$<C_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:-flto\;-s>
)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
add_link_options(
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<OR:$<C_COMPILER_ID:GNU>,$<C_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:-static>
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<C_COMPILER_ID:GNU>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:-static-libgcc>
    $<$<AND:$<NOT:$<OR:$<COMPILE_LANGUAGE:ASM_NASM>,$<COMPILE_LANGUAGE:ASM_MASM>>>,$<CXX_COMPILER_ID:GNU>,$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>>:-static-libstdc++>
)
